title : My Notes
name: '정락현 글감노트'
description: 'KBS비즈니스영상원 원장의 작업일지'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

# Markdown Processing
kramdown:
  input: GFM
  math_engine: mathjax

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  01fb:
    title: 페이스북 글감
    default_open: false
    output: true
  02blenderpython:
    title: 블렌더 파이썬
    default_open: false
    output: true
  03blockchainSTO:
    title: 블록체인 STO
    default_open: false
    output: true

defaults:
  - scope:
      type: 01fb
    values:
      title: Facebook & Wordlore
      permalink: /fb/:title
  - scope:
      type: 02blenderpython
    values:
      title: Blender,Machine Learning of Python
      permalink: /blenderpython/:title
  - scope:
      type: 03blockchainSTO
    values:
      title: blockchain, STO
      permalink: /blockchainSTO/:title


plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
