title : My Notes
name: '정락현 글감노트'
description: '로봇코딩을 위한 실업자들 작업일지'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

# Markdown Processing
kramdown:
  input: GFM
  math_engine: mathjax

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  _01fb:
    title: 생성AI그래픽 글감
    default_open: false
    output: true
  _02blenderpython:
    title: 블렌더 파이썬
    default_open: false
    output: true
  _03blockchainsto:
    title: The Jobless Robotcoding
    default_open: false
    output: true

defaults:
  - scope:
      type: 01fb
    values:
      title: Facebook & Wordlore
      permalink: /fb/:title
  - scope:
      type: 02blenderpython
    values:
      title: Blender,Machine Learning of Python
      permalink: /blenderpython/:title
  - scope:
      type: 03blockchainsto
    values:
      title: blockchain, sto
      permalink: /blockchainsto/:title


plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
